

library(el.convex)
tel_mean=function(m=50,mu0=0,mu1=0.5,threshold=10){
  x=rnorm(n = m, mean=mu0, sd=1)
  x1=rnorm(n = m, mean=mu1, sd=1)
  x5=mean(x)
  x8=mean(x1)
  c=3
  x9=numeric()
  h0=numeric()
  h1=numeric()
  for(i in 1:c){
    x9[i]=rnorm(n=1,mean=mu0,sd=1)
  }
  for(i in 1:c){
    h0[i]=x9[i]-x5
    h1[i]=x9[i]-x8
  }
  repeat{
    z=numeric()
    for(i in 1:(c-2)){
      x10=h0[i:c]
      x11=h1[i:c]
      l0=el.test.newton(x=x10,mu=0) 
      l1=el.test.newton(x=x11,mu=0) 
      if(abs(sum(l0$wts)-1)<0.01&abs(sum(l1$wts)-1)<0.01){
        tl0=l0$`-2LLR`*max(1-l0$`-2LLR`/length(x10),0.5)
        tl1=l1$`-2LLR`*max(1-l1$`-2LLR`/length(x11),0.5)
        z[i]=exp(0.5*(tl0-tl1))
      }
    }
    z=na.omit(z)
    if(length(z)==0){
      x9=c(x9,rnorm(n=1,mean=mu0,sd=1))
      c=c+1
      print(c)
      h0=c(h0,x9[c]-x5)
      h1=c(h1,x9[c]-x8)
    }
    if(length(z)>0){
      if(sum(z)<=threshold){
        x9=c(x9,rnorm(n=1,mean=mu0,sd=1))
        c=c+1
        print(c)
        h0=c(h0,x9[c]-x5)
        h1=c(h1,x9[c]-x8)
      }
    }
    if(length(z)>0){
      if(sum(z)>threshold){
        break
      }
    }
    if(c>100){
      break
    }
  }
  if(length(z)==0){
    z=c(0)
  }
  if(sum(z)<=threshold){
    repeat{
      z=numeric()
      current0=h0[(length(h0)-99):length(h0)]
      current1=h1[(length(h1)-99):length(h1)]
      for(i in 1:(length(current0)-2)){
        x10=current0[i:length(current0)]
        x11=current1[i:length(current0)]
        l0=el.test.newton(x=x10,mu=0) 
        l1=el.test.newton(x=x11,mu=0) 
        if(abs(sum(l0$wts)-1)<0.01&abs(sum(l1$wts)-1)<0.01){
          tl0=l0$`-2LLR`*max(1-l0$`-2LLR`/length(x10),0.5)
          tl1=l1$`-2LLR`*max(1-l1$`-2LLR`/length(x11),0.5)
          z[i]=exp(0.5*(tl0-tl1))
        }
      }
      z=na.omit(z)
      if(length(z)==0){
        x9=c(x9,rnorm(n=1,mean=mu0,sd=1))
        c=c+1
        print(c)
        h0=c(h0,x9[c]-x5)
        h1=c(h1,x9[c]-x8)
      }
      if(length(z)>0){
        if(sum(z)>threshold){
          print(sum(z))
          break
        }
      }
      if(length(z)>0){
        if(sum(z)<=threshold){
          x9=c(x9,rnorm(n=1,mean=mu0,sd=1))
          c=c+1
          print(c)
          print(sum(z))
          h0=c(h0,x9[c]-x5)
          h1=c(h1,x9[c]-x8)
        }
      }
      if(c>1000){
        break
      }
    }
  }
  return(c)
  
}






tel1_mean=function(m=100,mu0=0,mu1=0.5,threshold=200){
  false=0
  x=rnorm(n = m, mean=mu0, sd=1)
  x1=rnorm(n = m, mean=mu1, sd=1)
  x5=mean(x)
  x8=mean(x1)
  repeat{
    c=3
    repeat{
      x9=numeric()
      h0=numeric()
      h1=numeric()
      for(i in 1:c){
        x9[i]=rnorm(n=1,mean=mu0,sd=1)
      }
      for(i in 1:c){
        h0[i]=x9[i]-x5
        h1[i]=x9[i]-x8
      }
      repeat{
        z=numeric()
        for(i in 1:(c-2)){
          x10=h0[i:c]
          x11=h1[i:c]
          l0=el.test.newton(x=x10,mu=0) 
          l1=el.test.newton(x=x11,mu=0) 
          if(abs(sum(l0$wts)-1)<0.01&abs(sum(l1$wts)-1)<0.01){
            tl0=l0$`-2LLR`*max(1-l0$`-2LLR`/length(x10),0.5)
            tl1=l1$`-2LLR`*max(1-l1$`-2LLR`/length(x11),0.5)
            z[i]=exp(0.5*(tl0-tl1))
          }
        }
        z=na.omit(z)
        if(length(z)==0){
          x9=c(x9,rnorm(n=1,mean=mu0,sd=1))
          c=c+1
          print(c)
          h0=c(h0,x9[c]-x5)
          h1=c(h1,x9[c]-x8)
        }
        if(length(z)>0){
          if(sum(z)>threshold){
            break
          }
        }
        if(length(z)>0){
          if(sum(z)<=threshold){
            x9=c(x9,rnorm(n=1,mean=mu0,sd=1))
            c=c+1
            print(c)
            h0=c(h0,x9[c]-x5)
            h1=c(h1,x9[c]-x8)
          }
        }
        if(c>=49){
          break
        }
      }
      if(length(z)>0){
        if(sum(z)>threshold){
          false=false+1
          break
        }
      }
      if(c>=49){
        break
      }
    }
    if(c>=49){
      break
    }
    if(false>=10){
      break
    }
  }
  nodetect=0
  if(false<10){
  repeat{
    z=numeric()
    x9=c(x9,rnorm(n=1,mean=mu1,sd=1))
    c=c+1
    print(c)
    h0=c(h0,x9[c]-x5)
    h1=c(h1,x9[c]-x8)
    z=numeric()
    for(i in 1:(c-2)){
      x10=h0[i:c]
      x11=h1[i:c]
      l0=el.test.newton(x=x10,mu=0) 
      l1=el.test.newton(x=x11,mu=0) 
      if(abs(sum(l0$wts)-1)<0.01&abs(sum(l1$wts)-1)<0.01){
        tl0=l0$`-2LLR`*max(1-l0$`-2LLR`/length(x10),0.5)
        tl1=l1$`-2LLR`*max(1-l1$`-2LLR`/length(x11),0.5)
        z[i]=exp(0.5*(tl0-tl1))
      }
    }
    z=na.omit(z)
    if(length(z)==0){
      x9=c(x9,rnorm(n=1,mean=mu1,sd=1))
      c=c+1
      print(c)
      h0=c(h0,x9[c]-x5)
      h1=c(h1,x9[c]-x8)
    }
    if(length(z)>0){
      if(sum(z)>threshold){
        break
      }
    }
    if(length(z)>0){
      if(sum(z)<=threshold){
        x9=c(x9,rnorm(n=1,mean=mu1,sd=1))
        c=c+1
        print(c)
        h0=c(h0,x9[c]-x5)
        h1=c(h1,x9[c]-x8)
      }
    }
    if(c>=101){
      break
    }
  }
  if(length(z)==0){
    z=c(0)
  }
  if(sum(z)<=threshold){
    repeat{
      x9=c(x9,rnorm(n=1,mean=mu1,sd=1))
      c=c+1
      print(c)
      h0=c(h0,x9[c]-x5)
      h1=c(h1,x9[c]-x8)
      current0=h0[(length(h0)-99):length(h0)]
      current1=h1[(length(h1)-99):length(h1)]
      z=numeric()
      for(i in 1:(length(current0)-2)){
        x10=current0[i:length(current0)]
        x11=current1[i:length(current0)]
        l0=el.test.newton(x=x10,mu=0) 
        l1=el.test.newton(x=x11,mu=0) 
        if(abs(sum(l0$wts)-1)<0.01&abs(sum(l1$wts)-1)<0.01){
          tl0=l0$`-2LLR`*max(1-l0$`-2LLR`/length(x10),0.5)
          tl1=l1$`-2LLR`*max(1-l1$`-2LLR`/length(x11),0.5)
          z[i]=exp(0.5*(tl0-tl1))
        }
      }
      z=na.omit(z)
      if(length(z)==0){
        x9=c(x9,rnorm(n=1,mean=mu1,sd=1))
        c=c+1
        print(c)
        h0=c(h0,x9[c]-x5)
        h1=c(h1,x9[c]-x8)
      }
      if(length(z)>0){
        print(sum(z))
        if(sum(z)>threshold){
          break
        }
      }
      if(length(z)>0){
        print(sum(z))
        if(sum(z)<=threshold){
          x9=c(x9,rnorm(n=1,mean=mu1,sd=1))
          c=c+1
          print(c)
          h0=c(h0,x9[c]-x5)
          h1=c(h1,x9[c]-x8)
        }
      }
      if(c>1000){
        nodetect=nodetect+1
        break
      }
    }
  }
  return(c(c-50,nodetect))
  }
  if(false>=10){
    return("false")
  }
}


