el1_laplace=function(m=100,d=4,threshold=200,min0=-3,max0=3,min1=-3.5,max1=3.5,v=0){
  if(v<=3){
  x=matrix(0,nrow=m,ncol=d)
  for(i in 1:m){
    x[i,]=runif(n=d,min=min0,max=max0)
  }
  x1=matrix(0,ncol=1,nrow=m)
  x2=matrix(0,ncol=1,nrow=m)
  y1=rep(-0.5,times=d)
  y2=rep(0.5,times=d)
  for(i in 1:m){
    x1[i,]=exp(-y1%*%x[i,])
    x2[i,]=exp(-y2%*%x[i,])
  }
  x3=colMeans(x1)
  x4=colMeans(x2)
  x5=cbind(x3,x4)
  x7=matrix(0,nrow=m,ncol=2)
  x71=matrix(0,nrow=m,ncol=d)
  for(i in 1:m){
    x71[i,]=runif(n=d,min=min1,max=max1)
  }
  for(i in 1:m){
    x7[i,]=c(exp(-y1%*%x71[i,]),exp(-y2%*%x71[i,]))
  }
  x8=colMeans(x7)
  repeat{
    c=2+1
    repeat{
      x9=matrix(0,c,d)
      h0=matrix(0,c,2)
      h1=matrix(0,c,2)
      for(i in 1:c){
        if(c<v){
          x9[i,]=runif(n=d,min=min0,max=max0)
        }
        if(c>=v){
          x9[i,]=runif(n=d,min=min1,max=max1)
        }
      }
      for(i in 1:c){
        h0[i,]=c(exp(-y1%*%x9[i,]),exp(-y2%*%x9[i,]))-x5
        h1[i,]=c(exp(-y1%*%x9[i,]),exp(-y2%*%x9[i,]))-x8
      }
      z=numeric()
      repeat{
        for(i in 1:(c-2)){
          x10=h0[i:c,]
          x11=h1[i:c,]
          l0=el.test.newton(x=x10,mu=rep(0,2))
          l1=el.test.newton(x=x11,mu=rep(0,2))
          if(abs(sum(l0$wts)-1)<0.01&abs(sum(l1$wts)-1)<0.01){
            z[i]=exp(0.5*(l0$`-2LLR`-l1$`-2LLR`))
          }
        }
        z=na.omit(z)
        if(length(z)==0){
          x9=rbind(x9,runif(n=d,min=min1,max=max1))
          c=c+1
          print(c)
          h0=rbind(h0,c(exp(-y1%*%x9[i,]),exp(-y2%*%x9[i,]))-x5)
          h1=rbind(h1,c(exp(-y1%*%x9[i,]),exp(-y2%*%x9[i,]))-x8)
        }
        if(length(z)>0){
          if(sum(z)>threshold){
            break
          }
        }
        if(length(z)>0){
          if(sum(z)<=threshold){
            x9=rbind(x9,runif(n=d,min=min1,max=max1))
            c=c+1
            print(c)
            h0=rbind(h0,c(exp(-y1%*%x9[i,]),exp(-y2%*%x9[i,]))-x5)
            h1=rbind(h1,c(exp(-y1%*%x9[i,]),exp(-y2%*%x9[i,]))-x8)
          }
        }
        if(c>=49){
          break
        }
      }
      if(length(z)>0){
        if(sum(z)>threshold){
          break
        }
      }
      if(c>=49){
        break
      }
    }
    if(c>=49){
      break
    }
    if(length(z)>0){
      if(sum(z)>threshold){
        break
      }
    }
  }
  if(length(z)>0){
    if(sum(z)>threshold){
      delay=c-v
      false=0
      nodetect=0
      return(c(delay,false,nodetect))
    }
  }
    repeat{
      x9=rbind(x9,runif(n=d,min=min1,max=max1))
      c=c+1
      h0=rbind(h0,c(exp(-y1%*%x9[c,]),exp(-y2%*%x9[c,]))-x5)
      h1=rbind(h1,c(exp(-y1%*%x9[c,]),exp(-y2%*%x9[c,]))-x8)
      z=numeric()
      for(i in 1:(c-2)){
        x10=h0[i:c,]
        x11=h1[i:c,]
        l0=el.test.newton(x=x10,mu=rep(0,2))
        l1=el.test.newton(x=x11,mu=rep(0,2))
        if(abs(sum(l0$wts)-1)<0.01&abs(sum(l1$wts)-1)<0.01){
          z[i]=exp(0.5*(l0$`-2LLR`-l1$`-2LLR`))
        }
      }
      z=na.omit(z)
      if(length(z)==0){
        x9=rbind(x9,runif(n=d,min=min1,max=max1))
        c=c+1
        print(c)
        h0=rbind(h0,c(exp(-y1%*%x9[c,]),exp(-y2%*%x9[c,]))-x5)
        h1=rbind(h1,c(exp(-y1%*%x9[c,]),exp(-y2%*%x9[c,]))-x8)
      }
      if(length(z)>0){
        if(sum(z)>threshold){
          break
        }
      }
      if(length(z)>0){
        if(sum(z)<=threshold){
          x9=rbind(x9,runif(n=d,min=min1,max=max1))
          c=c+1
          print(c)
          h0=rbind(h0,c(exp(-y1%*%x9[c,]),exp(-y2%*%x9[c,]))-x5)
          h1=rbind(h1,c(exp(-y1%*%x9[c,]),exp(-y2%*%x9[c,]))-x8)
        }
      }
      if(c>=101){
        break
      }
    }
    if(length(z)==0){
      z=c(0)
    }
    if(sum(z)<=threshold){
      repeat{
        z=numeric()
        x9=rbind(x9,runif(n=d,min=min1,max=max1))
        h0=rbind(h0,c(exp(-y1%*%x9[c,]),exp(-y2%*%x9[c,]))-x5)
        h1=rbind(h1,c(exp(-y1%*%x9[c,]),exp(-y2%*%x9[c,]))-x8)
        current0=h0[(nrow(h0)-99):nrow(h0),]
        current1=h1[(nrow(h1)-99):nrow(h1),]
        z=numeric()
        for(i in 1:(nrow(current0)-2)){
          x10=current0[i:nrow(current0),]
          x11=current1[i:nrow(current0),]
          l0=el.test.newton(x=x10,mu=rep(0,2))
          l1=el.test.newton(x=x11,mu=rep(0,2))
          if(abs(sum(l0$wts)-1)<0.01&abs(sum(l1$wts)-1)<0.01){
            z[i]=exp(0.5*(l0$`-2LLR`-l1$`-2LLR`))
          }
        }
        z=na.omit(z)
        if(length(z)==0){
          x9=rbind(x9,runif(n=d,min=min1,max=max1))
          c=c+1
          print(c)
          h0=rbind(h0,c(exp(-y1%*%x9[c,]),exp(-y2%*%x9[c,]))-x5)
          h1=rbind(h1,c(exp(-y1%*%x9[c,]),exp(-y2%*%x9[c,]))-x8)
        }
        if(length(z)>0){
          if(sum(z)>threshold){
            break
          }
        }
        if(length(z)>0){
          print(sum(z))
          if(sum(z)<=threshold){
            x9=rbind(x9,runif(n=d,min=min1,max=max1))
            c=c+1
            print(c)
            h0=rbind(h0,c(exp(-y1%*%x9[c,]),exp(-y2%*%x9[c,]))-x5)
            h1=rbind(h1,c(exp(-y1%*%x9[c,]),exp(-y2%*%x9[c,]))-x8)
          }
        }
        if(c>1000){
          break
        }
      }
    }
  if(c<=1000){
    delay=c-v
    false=0
    nodetect=0
    return(c(delay,false,nodetect))
  }
  if(c>1000){
    delay=c-v
    false=0
    nodetect=1
    return(c(delay,false,nodetect))
  }
  }
  if(v>3){
    false=0
    x=matrix(0,nrow=m,ncol=d)
    for(i in 1:m){
      x[i,]=runif(n=d,min=min0,max=max0)
    }
    x1=matrix(0,ncol=1,nrow=m)
    x2=matrix(0,ncol=1,nrow=m)
    y1=rep(-0.5,times=d)
    y2=rep(0.5,times=d)
    for(i in 1:m){
      x1[i,]=exp(-y1%*%x[i,])
      x2[i,]=exp(-y2%*%x[i,])
    }
    x3=colMeans(x1)
    x4=colMeans(x2)
    x5=cbind(x3,x4)
    x7=matrix(0,nrow=m,ncol=2)
    x71=matrix(0,nrow=m,ncol=d)
    for(i in 1:m){
      x71[i,]=runif(n=d,min=min1,max=max1)
    }
    for(i in 1:m){
      x7[i,]=c(exp(-y1%*%x71[i,]),exp(-y2%*%x71[i,]))
    }
    x8=colMeans(x7)
    repeat{
      c=2+1
      repeat{
        x9=matrix(0,c,d)
        h0=matrix(0,c,2)
        h1=matrix(0,c,2)
        for(i in 1:c){
          x9[i,]=runif(n=d,min=min0,max=max0)
        }
        for(i in 1:c){
          h0[i,]=c(exp(-y1%*%x9[i,]),exp(-y2%*%x9[i,]))-x5
          h1[i,]=c(exp(-y1%*%x9[i,]),exp(-y2%*%x9[i,]))-x8
        }
        z=numeric()
        repeat{
          for(i in 1:(c-2)){
            x10=h0[i:c,]
            x11=h1[i:c,]
            l0=el.test.newton(x=x10,mu=rep(0,2))
            l1=el.test.newton(x=x11,mu=rep(0,2))
            if(abs(sum(l0$wts)-1)<0.01&abs(sum(l1$wts)-1)<0.01){
              z[i]=exp(0.5*(l0$`-2LLR`-l1$`-2LLR`))
            }
          }
          z=na.omit(z)
          if(length(z)==0){
            x9=rbind(x9,runif(n=d,min=min0,max=max0))
            c=c+1
            print(c)
            h0=rbind(h0,c(exp(-y1%*%x9[i,]),exp(-y2%*%x9[i,]))-x5)
            h1=rbind(h1,c(exp(-y1%*%x9[i,]),exp(-y2%*%x9[i,]))-x8)
          }
          if(length(z)>0){
            if(sum(z)>threshold){
              false=false+1
              break
            }
          }
          if(length(z)>0){
            if(sum(z)<=threshold){
              x9=rbind(x9,runif(n=d,min=min0,max=max0))
              c=c+1
              print(c)
              h0=rbind(h0,c(exp(-y1%*%x9[i,]),exp(-y2%*%x9[i,]))-x5)
              h1=rbind(h1,c(exp(-y1%*%x9[i,]),exp(-y2%*%x9[i,]))-x8)
            }
          }
          if(c>=v){
            break
          }
        }
        if(false>=1){
          break
        }
        if(c>=v){
          break
        }
      }
      if(c>=v){
        break
      }
      if(false>=1){
        break
      }
    }
    if(false<1){
      nodetect=0
      repeat{
        x9=rbind(x9,runif(n=d,min=min1,max=max1))
        c=c+1
        h0=rbind(h0,c(exp(-y1%*%x9[c,]),exp(-y2%*%x9[c,]))-x5)
        h1=rbind(h1,c(exp(-y1%*%x9[c,]),exp(-y2%*%x9[c,]))-x8)
        z=numeric()
        for(i in 1:(c-2)){
          x10=h0[i:c,]
          x11=h1[i:c,]
          l0=el.test.newton(x=x10,mu=rep(0,2))
          l1=el.test.newton(x=x11,mu=rep(0,2))
          if(abs(sum(l0$wts)-1)<0.01&abs(sum(l1$wts)-1)<0.01){
            z[i]=exp(0.5*(l0$`-2LLR`-l1$`-2LLR`))
          }
        }
        z=na.omit(z)
        if(length(z)==0){
          x9=rbind(x9,runif(n=d,min=min1,max=max1))
          c=c+1
          print(c)
          h0=rbind(h0,c(exp(-y1%*%x9[c,]),exp(-y2%*%x9[c,]))-x5)
          h1=rbind(h1,c(exp(-y1%*%x9[c,]),exp(-y2%*%x9[c,]))-x8)
        }
        if(length(z)>0){
          if(sum(z)>threshold){
            break
          }
        }
        if(length(z)>0){
          if(sum(z)<=threshold){
            x9=rbind(x9,runif(n=d,min=min1,max=max1))
            c=c+1
            print(c)
            h0=rbind(h0,c(exp(-y1%*%x9[c,]),exp(-y2%*%x9[c,]))-x5)
            h1=rbind(h1,c(exp(-y1%*%x9[c,]),exp(-y2%*%x9[c,]))-x8)
          }
        }
        if(c>=101){
          break
        }
      }
      if(length(z)==0){
        z=c(0)
      }
      if(sum(z)<=threshold){
        repeat{
          z=numeric()
          x9=rbind(x9,runif(n=d,min=min1,max=max1))
          h0=rbind(h0,c(exp(-y1%*%x9[c,]),exp(-y2%*%x9[c,]))-x5)
          h1=rbind(h1,c(exp(-y1%*%x9[c,]),exp(-y2%*%x9[c,]))-x8)
          current0=h0[(nrow(h0)-99):nrow(h0),]
          current1=h1[(nrow(h1)-99):nrow(h1),]
          z=numeric()
          for(i in 1:(nrow(current0)-2)){
            x10=current0[i:nrow(current0),]
            x11=current1[i:nrow(current0),]
            l0=el.test.newton(x=x10,mu=rep(0,2))
            l1=el.test.newton(x=x11,mu=rep(0,2))
            if(abs(sum(l0$wts)-1)<0.01&abs(sum(l1$wts)-1)<0.01){
              z[i]=exp(0.5*(l0$`-2LLR`-l1$`-2LLR`))
            }
          }
          z=na.omit(z)
          if(length(z)==0){
            x9=rbind(x9,runif(n=d,min=min1,max=max1))
            c=c+1
            print(c)
            h0=rbind(h0,c(exp(-y1%*%x9[c,]),exp(-y2%*%x9[c,]))-x5)
            h1=rbind(h1,c(exp(-y1%*%x9[c,]),exp(-y2%*%x9[c,]))-x8)
          }
          if(length(z)>0){
            if(sum(z)>threshold){
              break
            }
          }
          if(length(z)>0){
            print(sum(z))
            if(sum(z)<=threshold){
              x9=rbind(x9,runif(n=d,min=min1,max=max1))
              c=c+1
              print(c)
              h0=rbind(h0,c(exp(-y1%*%x9[c,]),exp(-y2%*%x9[c,]))-x5)
              h1=rbind(h1,c(exp(-y1%*%x9[c,]),exp(-y2%*%x9[c,]))-x8)
            }
          }
          if(c>1000){
            nodetect=nodetect+1
            break
          }
        }
      }
      return(c(c-v,false,nodetect))
    }
    if(false>=1){
      return(c(NA,false,NA))
    }
  }
}

el_laplace=function(m=100,d=4,threshold=200,min0=-3,max0=3,min1=-3.5,max1=3.5,trunction=1000){
  x=matrix(0,nrow=m,ncol=d)
  for(i in 1:m){
    x[i,]=runif(n=d,min=min0,max=max0)
  }
  x1=matrix(0,ncol=1,nrow=m)
  x2=matrix(0,ncol=1,nrow=m)
  y1=rep(-0.5,times=d)
  y2=rep(0.5,times=d)
  for(i in 1:m){
    x1[i,]=exp(-y1%*%x[i,])
    x2[i,]=exp(-y2%*%x[i,])
  }
  x3=colMeans(x1)
  x4=colMeans(x2)
  x5=cbind(x3,x4)
  x7=matrix(0,nrow=m,ncol=2)
  x71=matrix(0,nrow=m,ncol=d)
  for(i in 1:m){
    x71[i,]=runif(n=d,min=min1,max=max1)
  }
  for(i in 1:m){
    x7[i,]=c(exp(-y1%*%x71[i,]),exp(-y2%*%x71[i,]))
  }
  x8=colMeans(x7)
  c=2+1
  x9=matrix(0,c,d)
  h0=matrix(0,c,2)
  h1=matrix(0,c,2)
  for(i in 1:c){
    x9[i,]=runif(n=d,min=min0,max=max0)
  }
  for(i in 1:c){
    h0[i,]=c(exp(-y1%*%x9[i,]),exp(-y2%*%x9[i,]))-x5
    h1[i,]=c(exp(-y1%*%x9[i,]),exp(-y2%*%x9[i,]))-x8
  }
  z=numeric()
  repeat{
    for(i in 1:(c-2)){
      x10=h0[i:c,]
      x11=h1[i:c,]
      l0=el.test.newton(x=x10,mu=rep(0,2))
      l1=el.test.newton(x=x11,mu=rep(0,2))
      if(abs(sum(l0$wts)-1)<0.01&abs(sum(l1$wts)-1)<0.01){
        z[i]=exp(0.5*(l0$`-2LLR`-l1$`-2LLR`))
      }
    }
    z=na.omit(z)
    if(length(z)==0){
      x9=rbind(x9,runif(n=d,min=min0,max=max0))
      c=c+1
      print(c)
      h0=rbind(h0,c(exp(-y1%*%x9[c,]),exp(-y2%*%x9[c,]))-x5)
      h1=rbind(h1,c(exp(-y1%*%x9[c,]),exp(-y2%*%x9[c,]))-x8)
    }
    if(length(z)>0){
      if(sum(z)<=threshold){
        x9=rbind(x9,runif(n=d,min=min0,max=max0))
        c=c+1
        print(c)
        h0=rbind(h0,c(exp(-y1%*%x9[c,]),exp(-y2%*%x9[c,]))-x5)
        h1=rbind(h1,c(exp(-y1%*%x9[c,]),exp(-y2%*%x9[c,]))-x8)
      }
    }
    if(length(z)>0){
      if(sum(z)>threshold){
        break
      }
    }
    if(c>100){
      break
    }
  }
  if(length(z)==0){
    z=c(0)
  }
  if(sum(z)<=threshold){
    repeat{
      current0=h0[(nrow(h0)-99):nrow(h0),]
      current1=h1[(nrow(h1)-99):nrow(h1),]
      z=numeric()
      for(i in 1:(nrow(current0)-2)){
        x10=current0[i:nrow(current0),]
        x11=current1[i:nrow(current0),]
        l0=el.test.newton(x=x10,mu=rep(0,2))
        l1=el.test.newton(x=x11,mu=rep(0,2))
        if(abs(sum(l0$wts)-1)<0.01&abs(sum(l1$wts)-1)<0.01){
          z[i]=exp(0.5*(l0$`-2LLR`-l1$`-2LLR`))
        }
      }
      z=na.omit(z)
      if(length(z)==0){
        x9=rbind(x9,runif(n=d,min=min0,max=max0))
        c=c+1
        print(c)
        h0=rbind(h0,c(exp(-y1%*%x9[c,]),exp(-y2%*%x9[c,]))-x5)
        h1=rbind(h1,c(exp(-y1%*%x9[c,]),exp(-y2%*%x9[c,]))-x8)
      }
      if(length(z)>0){
        print(sum(z))
        if(sum(z)>threshold){
          break
        }
      }
      if(length(z)>0){
        print(sum(z))
        if(sum(z)<=threshold){
          x9=rbind(x9,runif(n=d,min=min0,max=max0))
          c=c+1
          print(c)
          h0=rbind(h0,c(exp(-y1%*%x9[c,]),exp(-y2%*%x9[c,]))-x5)
          h1=rbind(h1,c(exp(-y1%*%x9[c,]),exp(-y2%*%x9[c,]))-x8)
        }
      }
      if(c>=trunction){
        break
      }
    }
  }
  return(c)
}