


library(el.convex)
ael_mean=function(m=100,d=2,mu1=rep(0.5,times=d),threshold=200,trunction=1000){
  x=matrix(0,nrow=m,ncol=d)
  for(i in 1:m){
    x[i,]=rgamma(n=d,shape=9,rate=2)
  }
  x5=colMeans(x)
  x8=x5+mu1
  c=d+1
  if(c<=100){
    x9=matrix(0,c,d)
    h0=matrix(0,c,d)
    h1=matrix(0,c,d)
    for(i in 1:c){
      x9[i,]=rgamma(n=d,shape=9,rate=2)
    }
    for(i in 1:c){
      h0[i,]=x9[i,]-x5
      h1[i,]=x9[i,]-x8
    }
    z=numeric()
    repeat{
      for(i in 1:(c-(d-1))){
        x10=h0[i:c,]
        x11=h1[i:c,]
        x10s=colMeans(x10)
        x11s=colMeans(x11)
        x10=rbind(x10,-max(1,log(c)/2)*x10s)
        x11=rbind(x11,-max(1,log(c)/2)*x11s)
        l0=el.test.newton(x=x10,mu=rep(0,d)) 
        l1=el.test.newton(x=x11,mu=rep(0,d)) 
        z[i]= (-0.5*l1$`-2LLR`+0.5*l0$`-2LLR`)
      }
      if(max(z)>threshold){
        break
      }
      x9=rbind(x9,rgamma(n=d,shape=9,rate=2))
      c=c+1
      print(c)
      h0=rbind(h0,x9[c,]-x5)
      h1=rbind(h1,x9[c,]-x8)
      if(c>100){
        break
      }
    }
  }
  if(max(z)<=threshold){
    repeat{
      current0=h0[(nrow(h0)-99):nrow(h0),]
      current1=h1[(nrow(h1)-99):nrow(h1),]
      z=numeric()
      for(i in 1:(nrow(current0)-(d-1))){
        x10=current0[i:nrow(current0),]
        x11=current1[i:nrow(current0),]
        x10s=colMeans(x10)
        x11s=colMeans(x11)
        x10=rbind(x10,-max(1,log(c)/2)*x10s)
        x11=rbind(x11,-max(1,log(c)/2)*x11s)
        l0=el.test.newton(x=x10,mu=rep(0,d)) 
        l1=el.test.newton(x=x11,mu=rep(0,d)) 
        z[i]= (-0.5*l1$`-2LLR`+0.5*l0$`-2LLR`)
      }
      print(max(z))
      if(max(z)>threshold){
        break
      }
      x9=rbind(x9,rgamma(n=d,shape=9,rate=2))
      c=c+1
      print(c)
      h0=rbind(h0,x9[c,]-x5)
      h1=rbind(h1,x9[c,]-x8)
      if(c>trunction){
        break
      }
    }
  }
  return(c)
}

ael1_mean=function(m=100,d=2,mu1=rep(0.5,times=d),threshold=200,v=0){
  if(v<=d+1){
    x=matrix(0,nrow=m,ncol=d)
    for(i in 1:m){
      x[i,]=rgamma(n=d,shape=9,rate=2)
    }
    x5=colMeans(x)
    x8=x5+mu1
    repeat{
      c=d+1
      repeat{
        x9=matrix(0,c,d)
        h0=matrix(0,c,d)
        h1=matrix(0,c,d)
        for(i in 1:c){
          if(i<v){
            x9[i,]=rgamma(n=d,shape=9,rate=2)
          }
          if(i>=v){
            x9[i,]=rgamma(n=d,shape=9,rate=2)+mu1
          }
        }
        for(i in 1:c){
          h0[i,]=x9[i,]-x5
          h1[i,]=x9[i,]-x8
        }
        z=numeric()
        repeat{
          for(i in 1:(c-(d-1))){
            x10=h0[i:c,]
            x11=h1[i:c,]
            x10s=colMeans(x10)
            x11s=colMeans(x11)
            x10=rbind(x10,-max(1,log(c)/2)*x10s)
            x11=rbind(x11,-max(1,log(c)/2)*x11s)
            l0=el.test.newton(x=x10,mu=rep(0,d))
            l1=el.test.newton(x=x11,mu=rep(0,d))
            z[i]= (-0.5*l1$`-2LLR`+0.5*l0$`-2LLR`)
          }
          if(max(z)>threshold){
            break
          }
          c=c+1
          if(c>=50){
            break
          }
          x9=rbind(x9,rgamma(n=d,shape=9,rate=2)+mu1)
          h0=rbind(h0,x9[c,]-x5)
          h1=rbind(h1,x9[c,]-x8)
        }
        if(max(z)>threshold){
      
          break
        }
        if(c>=50){
          break
        }
      }
      if(c>=50){
        break
      }
      if(max(z)>threshold){
        break
      }
    }
    if(max(z)>threshold){
      delay=c-v
      false=0
      nodetect=0
      return(c(delay,false,nodetect))
    }
      nodetect=0
      repeat{
        x9=rbind(x9,rgamma(n=d,shape=9,rate=2)+mu1)
        h0=rbind(h0,x9[c,]-x5)
        h1=rbind(h1,x9[c,]-x8)
        z=numeric()
        for(i in 1:(c-(d-1))){
          x10=h0[i:c,]
          x11=h1[i:c,]
          x10s=colMeans(x10)
          x11s=colMeans(x11)
          x10=rbind(x10,-max(1,log(c)/2)*x10s)
          x11=rbind(x11,-max(1,log(c)/2)*x11s)
          l0=el.test.newton(x=x10,mu=rep(0,d))
          l1=el.test.newton(x=x11,mu=rep(0,d))
          z[i]= (-0.5*l1$`-2LLR`+0.5*l0$`-2LLR`)
        }
        c=c+1
        if(max(z)>threshold){
          break
        }
        if(c>=101){
          break
        }
      }
      if(max(z)<=threshold){
        repeat{
          x9=rbind(x9,rgamma(n=d,shape=9,rate=2)+mu1)
          h0=rbind(h0,x9[c,]-x5)
          h1=rbind(h1,x9[c,]-x8)
          current0=h0[(nrow(h0)-99):nrow(h0),]
          current1=h1[(nrow(h1)-99):nrow(h1),]
          z=numeric()
          for(i in 1:(nrow(current0)-(d-1))){
            x10=current0[i:nrow(current0),]
            x11=current1[i:nrow(current0),]
            x10s=colMeans(x10)
            x11s=colMeans(x11)
            x10=rbind(x10,-max(1,log(c)/2)*x10s)
            x11=rbind(x11,-max(1,log(c)/2)*x11s)
            l0=el.test.newton(x=x10,mu=rep(0,d))
            l1=el.test.newton(x=x11,mu=rep(0,d))
            z[i]= (-0.5*l1$`-2LLR`+0.5*l0$`-2LLR`)
          }
          print(max(z))
          if(max(z)>threshold){
            break
          }
          c=c+1
          print(c)
          if(max(z)>threshold){
            break
          }
          if(c>1000){
            nodetect=nodetect+1
            break
          }
        }
      }
      if(c<=1000){
        delay=c-v
        false=0
        nodetect=0
        return(c(delay,false,nodetect))
      }
      if(c>1000){
        delay=c-v
        false=0
        nodetect=1
        return(c(delay,false,nodetect))
      }
    }
    if(v>d+1){
      false=0
  x=matrix(0,nrow=m,ncol=d)
  for(i in 1:m){
    x[i,]=rgamma(n=d,shape=9,rate=2)
  }
  x5=colMeans(x)
  x8=x5+mu1
  repeat{
    c=d+1
    repeat{
      x9=matrix(0,c,d)
      h0=matrix(0,c,d)
      h1=matrix(0,c,d)
      for(i in 1:c){
        x9[i,]=rgamma(n=d,shape=9,rate=2)
      }
      for(i in 1:c){
        h0[i,]=x9[i,]-x5
        h1[i,]=x9[i,]-x8
      }
      z=numeric()
      repeat{
        for(i in 1:(c-(d-1))){
          x10=h0[i:c,]
          x11=h1[i:c,]
          x10s=colMeans(x10)
          x11s=colMeans(x11)
          x10=rbind(x10,-max(1,log(c)/2)*x10s)
          x11=rbind(x11,-max(1,log(c)/2)*x11s)
          l0=el.test.newton(x=x10,mu=rep(0,d))
          l1=el.test.newton(x=x11,mu=rep(0,d))
          z[i]= (-0.5*l1$`-2LLR`+0.5*l0$`-2LLR`)
        }
        if(max(z)>threshold){
          break
        }
        c=c+1
        if(c>=v){
          break
        }
        x9=rbind(x9,rgamma(n=d,shape=9,rate=2))
        h0=rbind(h0,x9[c,]-x5)
        h1=rbind(h1,x9[c,]-x8)
      }
      if(max(z)>threshold){
        false=false+1
        break
      }
      if(c>=v){
        break
      }
    }
    if(c>=v){
      break
    }
    if(false>=1){
      break
    }
  }
  if(false<1){
  nodetect=0
  repeat{
    x9=rbind(x9,rgamma(n=d,shape=9,rate=2)+mu1)
    h0=rbind(h0,x9[c,]-x5)
    h1=rbind(h1,x9[c,]-x8)
    z=numeric()
    for(i in 1:(c-(d-1))){
      x10=h0[i:c,]
      x11=h1[i:c,]
      x10s=colMeans(x10)
      x11s=colMeans(x11)
      x10=rbind(x10,-max(1,log(c)/2)*x10s)
      x11=rbind(x11,-max(1,log(c)/2)*x11s)
      l0=el.test.newton(x=x10,mu=rep(0,d))
      l1=el.test.newton(x=x11,mu=rep(0,d))
      z[i]= (-0.5*l1$`-2LLR`+0.5*l0$`-2LLR`)
    }
    c=c+1
    if(max(z)>threshold){
      break
    }
    if(c>=101){
      break
    }
  }
  if(max(z)<=threshold){
    repeat{
      x9=rbind(x9,rgamma(n=d,shape=9,rate=2)+mu1)
      h0=rbind(h0,x9[c,]-x5)
      h1=rbind(h1,x9[c,]-x8)
      current0=h0[(nrow(h0)-99):nrow(h0),]
      current1=h1[(nrow(h1)-99):nrow(h1),]
      z=numeric()
      for(i in 1:(nrow(current0)-(d-1))){
        x10=current0[i:nrow(current0),]
        x11=current1[i:nrow(current0),]
        x10s=colMeans(x10)
        x11s=colMeans(x11)
        x10=rbind(x10,-max(1,log(c)/2)*x10s)
        x11=rbind(x11,-max(1,log(c)/2)*x11s)
        l0=el.test.newton(x=x10,mu=rep(0,d))
        l1=el.test.newton(x=x11,mu=rep(0,d))
        z[i]= (-0.5*l1$`-2LLR`+0.5*l0$`-2LLR`)
      }
      print(max(z))
      if(max(z)>threshold){
        break
      }
      c=c+1
      print(c)
      if(max(z)>threshold){
        break
      }
      if(c>1000){
        nodetect=nodetect+1
        break
      }
    }
  }
  return(c(c-v,false,nodetect))
  }
  if(false>=1){
    return(c(NA,false,NA))
  }
    }
}
