tel1_laplace=function(m=100,d=2,threshold=200,lambda0=4,lambda1=4.5,v=0){
 if(v==0|v==1){
   x=matrix(0,nrow=m,ncol=d)
   for(i in 1:m){
     x[i,]=rpois(n=d,lambda=lambda0)
   }
   x1=matrix(0,ncol=1,nrow=m)
   x2=matrix(0,ncol=1,nrow=m)
   y1=rep(-0.5,times=d)
   y2=rep(0.5,times=d)
   for(i in 1:m){
     x1[i,]=exp(-y1%*%x[i,])
     x2[i,]=exp(-y2%*%x[i,])
   }
   x3=colMeans(x1)
   x4=colMeans(x2)
   x5=cbind(x3,x4)
   x7=matrix(0,nrow=m,ncol=2)
   x71=matrix(0,nrow=m,ncol=d)
   for(i in 1:m){
     x71[i,]=rpois(n=d,lambda=lambda1)
   }
   for(i in 1:m){
     x7[i,]=c(exp(-y1%*%x71[i,]),exp(-y2%*%x71[i,]))
   }
   x8=colMeans(x7)
   repeat{
     c=2+1
     repeat{
       x9=matrix(0,c,d)
       h0=matrix(0,c,2)
       h1=matrix(0,c,2)
       for(i in 1:c){
         x9[i,]=rpois(n=d,lambda=lambda1)
       }
       for(i in 1:c){
         h0[i,]=c(exp(-y1%*%x9[i,]),exp(-y2%*%x9[i,]))-x5
         h1[i,]=c(exp(-y1%*%x9[i,]),exp(-y2%*%x9[i,]))-x8
       }
       z=numeric()
       repeat{
         for(i in 1:(c-2)){
           x10=h0[i:c,]
           x11=h1[i:c,]
           l0=el.test.newton(x=x10,mu=rep(0,2)) 
           l1=el.test.newton(x=x11,mu=rep(0,2)) 
           if(abs(sum(l0$wts)-1)<0.01&abs(sum(l1$wts)-1)<0.01){
             tl0=l0$`-2LLR`*max(1-l0$`-2LLR`/nrow(x10),0.5)
             tl1=l1$`-2LLR`*max(1-l1$`-2LLR`/nrow(x11),0.5)
             z[i]=exp(0.5*(tl0-tl1))
           }
         }
         z=na.omit(z)
         if(length(z)==0){
           x9=rbind(x9,rpois(n=d,lambda=lambda1))
           c=c+1
           print(c)
           h0=rbind(h0,c(exp(-y1%*%x9[i,]),exp(-y2%*%x9[i,]))-x5)
           h1=rbind(h1,c(exp(-y1%*%x9[i,]),exp(-y2%*%x9[i,]))-x8)
         }
         if(length(z)>0){
           if(sum(z)>threshold){
             break
           }
         }
         if(length(z)>0){
           if(sum(z)<=threshold){
             x9=rbind(x9,rpois(n=d,lambda=lambda1))
             c=c+1
             print(c)
             h0=rbind(h0,c(exp(-y1%*%x9[i,]),exp(-y2%*%x9[i,]))-x5)
             h1=rbind(h1,c(exp(-y1%*%x9[i,]),exp(-y2%*%x9[i,]))-x8)
           }
         }
         if(c>=49){
           break
         }
       }
       if(length(z)>0){
          if(sum(z)>threshold){
         break
       }
       }
       if(c>=49){
         break
       }
     }
     if(c>=49){
       break
     }
     if(length(z)>0){
       if(sum(z)>threshold){
         break
       }
     }
   }
   if(length(z)>0){
     if(sum(z)>threshold){
       delay=c
       false=0
       nodetect=0
       return(c(delay,false,nodetect))
     }
   }
     repeat{
       x9=rbind(x9,rpois(n=d,lambda=lambda1))
       c=c+1
       h0=rbind(h0,c(exp(-y1%*%x9[c,]),exp(-y2%*%x9[c,]))-x5)
       h1=rbind(h1,c(exp(-y1%*%x9[c,]),exp(-y2%*%x9[c,]))-x8)
       z=numeric()
       for(i in 1:(c-2)){
         x10=h0[i:c,]
         x11=h1[i:c,]
         l0=el.test.newton(x=x10,mu=rep(0,2)) 
         l1=el.test.newton(x=x11,mu=rep(0,2)) 
         if(abs(sum(l0$wts)-1)<0.01&abs(sum(l1$wts)-1)<0.01){
           tl0=l0$`-2LLR`*max(1-l0$`-2LLR`/nrow(x10),0.5)
           tl1=l1$`-2LLR`*max(1-l1$`-2LLR`/nrow(x11),0.5)
           z[i]=exp(0.5*(tl0-tl1))
         }
       }
       z=na.omit(z)
       if(length(z)==0){
         x9=rbind(x9,rpois(n=d,lambda=lambda1))
         c=c+1
         print(c)
         h0=rbind(h0,c(exp(-y1%*%x9[c,]),exp(-y2%*%x9[c,]))-x5)
         h1=rbind(h1,c(exp(-y1%*%x9[c,]),exp(-y2%*%x9[c,]))-x8)
       }
       if(length(z)>0){
         if(sum(z)>threshold){
           break
         }
       }
       if(length(z)>0){
         if(sum(z)<=threshold){
           x9=rbind(x9,rpois(n=d,lambda=lambda1))
           c=c+1
           print(c)
           h0=rbind(h0,c(exp(-y1%*%x9[c,]),exp(-y2%*%x9[c,]))-x5)
           h1=rbind(h1,c(exp(-y1%*%x9[c,]),exp(-y2%*%x9[c,]))-x8)
         }
       }
       if(c>=101){
         break
       }
     }
   if(length(z)>0){
     if(sum(z)>threshold){
       delay=c
       false=0
       nodetect=0
       return(c(delay,false,nodetect))
     }
   }
     if(length(z)==0){
       z=c(0)
     }
     if(sum(z)<=threshold){
       repeat{
         z=numeric()
         x9=rbind(x9,rpois(n=d,lambda=lambda1))
         h0=rbind(h0,c(exp(-y1%*%x9[c,]),exp(-y2%*%x9[c,]))-x5)
         h1=rbind(h1,c(exp(-y1%*%x9[c,]),exp(-y2%*%x9[c,]))-x8)
         current0=h0[(nrow(h0)-99):nrow(h0),]
         current1=h1[(nrow(h1)-99):nrow(h1),]
         z=numeric()
         for(i in 1:(nrow(current0)-2)){
           x10=current0[i:nrow(current0),]
           x11=current1[i:nrow(current0),]
           l0=el.test.newton(x=x10,mu=rep(0,2)) 
           l1=el.test.newton(x=x11,mu=rep(0,2)) 
           if(abs(sum(l0$wts)-1)<0.01&abs(sum(l1$wts)-1)<0.01){
             tl0=l0$`-2LLR`*max(1-l0$`-2LLR`/nrow(x10),0.5)
             tl1=l1$`-2LLR`*max(1-l1$`-2LLR`/nrow(x11),0.5)
             z[i]=exp(0.5*(tl0-tl1))
           }
         }
         z=na.omit(z)
         if(length(z)==0){
           x9=rbind(x9,rpois(n=d,lambda=lambda1))
           c=c+1
           print(c)
           h0=rbind(h0,c(exp(-y1%*%x9[c,]),exp(-y2%*%x9[c,]))-x5)
           h1=rbind(h1,c(exp(-y1%*%x9[c,]),exp(-y2%*%x9[c,]))-x8)
         }
         if(length(z)>0){
           if(sum(z)>threshold){
             break
           }
         }
         if(length(z)>0){
           print(sum(z))
           if(sum(z)<=threshold){
             x9=rbind(x9,rpois(n=d,lambda=lambda1))
             c=c+1
             print(c)
             h0=rbind(h0,c(exp(-y1%*%x9[c,]),exp(-y2%*%x9[c,]))-x5)
             h1=rbind(h1,c(exp(-y1%*%x9[c,]),exp(-y2%*%x9[c,]))-x8)
           }
         }
         if(c>1000){
           break
         }
       }
     }
   if(c<=1000){
     delay=c
     false=0
     nodetect=0
     return(c(delay,false,nodetect))
   }
   if(c>1000){
     delay=c
     false=0
     nodetect=1
     return(c(delay,false,nodetect))
   }
 }
 
  if(v==2|v==3){
    x=matrix(0,nrow=m,ncol=d)
    for(i in 1:m){
      x[i,]=rpois(n=d,lambda=lambda0)
    }
    x1=matrix(0,ncol=1,nrow=m)
    x2=matrix(0,ncol=1,nrow=m)
    y1=rep(-0.5,times=d)
    y2=rep(0.5,times=d)
    for(i in 1:m){
      x1[i,]=exp(-y1%*%x[i,])
      x2[i,]=exp(-y2%*%x[i,])
    }
    x3=colMeans(x1)
    x4=colMeans(x2)
    x5=cbind(x3,x4)
    x7=matrix(0,nrow=m,ncol=2)
    x71=matrix(0,nrow=m,ncol=d)
    for(i in 1:m){
      x71[i,]=rpois(n=d,lambda=lambda1)
    }
    for(i in 1:m){
      x7[i,]=c(exp(-y1%*%x71[i,]),exp(-y2%*%x71[i,]))
    }
    x8=colMeans(x7)
    repeat{
      c=2+1
      repeat{
        x9=matrix(0,c,d)
        h0=matrix(0,c,2)
        h1=matrix(0,c,2)
        for(i in 1:c){
          if(c<v){
            x9[i,]=rpois(n=d,lambda=lambda0)
          }
          if(c>=v)
            x9[i,]=rpois(n=d,lambda=lambda1)
        }
        for(i in 1:c){
          h0[i,]=c(exp(-y1%*%x9[i,]),exp(-y2%*%x9[i,]))-x5
          h1[i,]=c(exp(-y1%*%x9[i,]),exp(-y2%*%x9[i,]))-x8
        }
        z=numeric()
        repeat{
          for(i in 1:(c-2)){
            x10=h0[i:c,]
            x11=h1[i:c,]
            l0=el.test.newton(x=x10,mu=rep(0,2)) 
            l1=el.test.newton(x=x11,mu=rep(0,2)) 
            if(abs(sum(l0$wts)-1)<0.01&abs(sum(l1$wts)-1)<0.01){
              tl0=l0$`-2LLR`*max(1-l0$`-2LLR`/nrow(x10),0.5)
              tl1=l1$`-2LLR`*max(1-l1$`-2LLR`/nrow(x11),0.5)
              z[i]=exp(0.5*(tl0-tl1))
            }
          }
          z=na.omit(z)
          if(length(z)==0){
            x9=rbind(x9,rpois(n=d,lambda=lambda1))
            c=c+1
            print(c)
            h0=rbind(h0,c(exp(-y1%*%x9[i,]),exp(-y2%*%x9[i,]))-x5)
            h1=rbind(h1,c(exp(-y1%*%x9[i,]),exp(-y2%*%x9[i,]))-x8)
          }
          if(length(z)>0){
            if(sum(z)>threshold){
              break
            }
          }
          if(length(z)>0){
            if(sum(z)<=threshold){
              x9=rbind(x9,rpois(n=d,lambda=lambda1))
              c=c+1
              print(c)
              h0=rbind(h0,c(exp(-y1%*%x9[i,]),exp(-y2%*%x9[i,]))-x5)
              h1=rbind(h1,c(exp(-y1%*%x9[i,]),exp(-y2%*%x9[i,]))-x8)
            }
          }
          if(c>=49){
            break
          }
        }
        if(length(z)>0){
          if(sum(z)>threshold){
            break
          }
        }
        if(c>=49){
          break
        }
      }
      if(c>=49){
        break
      }
      if(length(z)>0){
        if(sum(z)>threshold){
          break
        }
      }
    }
    if(length(z)>0){
      if(sum(z)>threshold){
        delay=c-v
        false=0
        nodetect=0
        return(c(delay,false,nodetect))
      }
    }
    repeat{
      x9=rbind(x9,rpois(n=d,lambda=lambda1))
      c=c+1
      h0=rbind(h0,c(exp(-y1%*%x9[c,]),exp(-y2%*%x9[c,]))-x5)
      h1=rbind(h1,c(exp(-y1%*%x9[c,]),exp(-y2%*%x9[c,]))-x8)
      z=numeric()
      for(i in 1:(c-2)){
        x10=h0[i:c,]
        x11=h1[i:c,]
        l0=el.test.newton(x=x10,mu=rep(0,2)) 
        l1=el.test.newton(x=x11,mu=rep(0,2)) 
        if(abs(sum(l0$wts)-1)<0.01&abs(sum(l1$wts)-1)<0.01){
          tl0=l0$`-2LLR`*max(1-l0$`-2LLR`/nrow(x10),0.5)
          tl1=l1$`-2LLR`*max(1-l1$`-2LLR`/nrow(x11),0.5)
          z[i]=exp(0.5*(tl0-tl1))
        }
      }
      z=na.omit(z)
      if(length(z)==0){
        x9=rbind(x9,rpois(n=d,lambda=lambda1))
        c=c+1
        print(c)
        h0=rbind(h0,c(exp(-y1%*%x9[c,]),exp(-y2%*%x9[c,]))-x5)
        h1=rbind(h1,c(exp(-y1%*%x9[c,]),exp(-y2%*%x9[c,]))-x8)
      }
      if(length(z)>0){
        if(sum(z)>threshold){
          break
        }
      }
      if(length(z)>0){
        if(sum(z)<=threshold){
          x9=rbind(x9,rpois(n=d,lambda=lambda1))
          c=c+1
          print(c)
          h0=rbind(h0,c(exp(-y1%*%x9[c,]),exp(-y2%*%x9[c,]))-x5)
          h1=rbind(h1,c(exp(-y1%*%x9[c,]),exp(-y2%*%x9[c,]))-x8)
        }
      }
      if(c>=101){
        break
      }
    }
    if(length(z)>0){
      if(sum(z)>threshold){
        delay=c-v
        false=0
        nodetect=0
        return(c(delay,false,nodetect))
      }
    }
    if(length(z)==0){
      z=c(0)
    }
    if(sum(z)<=threshold){
      repeat{
        z=numeric()
        x9=rbind(x9,rpois(n=d,lambda=lambda1))
        h0=rbind(h0,c(exp(-y1%*%x9[c,]),exp(-y2%*%x9[c,]))-x5)
        h1=rbind(h1,c(exp(-y1%*%x9[c,]),exp(-y2%*%x9[c,]))-x8)
        current0=h0[(nrow(h0)-99):nrow(h0),]
        current1=h1[(nrow(h1)-99):nrow(h1),]
        z=numeric()
        for(i in 1:(nrow(current0)-2)){
          x10=current0[i:nrow(current0),]
          x11=current1[i:nrow(current0),]
          l0=el.test.newton(x=x10,mu=rep(0,2)) 
          l1=el.test.newton(x=x11,mu=rep(0,2)) 
          if(abs(sum(l0$wts)-1)<0.01&abs(sum(l1$wts)-1)<0.01){
            tl0=l0$`-2LLR`*max(1-l0$`-2LLR`/nrow(x10),0.5)
            tl1=l1$`-2LLR`*max(1-l1$`-2LLR`/nrow(x11),0.5)
            z[i]=exp(0.5*(tl0-tl1))
          }
        }
        z=na.omit(z)
        if(length(z)==0){
          x9=rbind(x9,rpois(n=d,lambda=lambda1))
          c=c+1
          print(c)
          h0=rbind(h0,c(exp(-y1%*%x9[c,]),exp(-y2%*%x9[c,]))-x5)
          h1=rbind(h1,c(exp(-y1%*%x9[c,]),exp(-y2%*%x9[c,]))-x8)
        }
        if(length(z)>0){
          if(sum(z)>threshold){
            break
          }
        }
        if(length(z)>0){
          print(sum(z))
          if(sum(z)<=threshold){
            x9=rbind(x9,rpois(n=d,lambda=lambda1))
            c=c+1
            print(c)
            h0=rbind(h0,c(exp(-y1%*%x9[c,]),exp(-y2%*%x9[c,]))-x5)
            h1=rbind(h1,c(exp(-y1%*%x9[c,]),exp(-y2%*%x9[c,]))-x8)
          }
        }
        if(c>1000){
          break
        }
      }
    }
    if(c<=1000){
      delay=c-v
      false=0
      nodetect=0
      return(c(delay,false,nodetect))
    }
    if(c>1000){
      delay=c-v
      false=0
      nodetect=1
      return(c(delay,false,nodetect))
    }
  }
  if(v>=4){
    false=0
    x=matrix(0,nrow=m,ncol=d)
    for(i in 1:m){
      x[i,]=rpois(n=d,lambda=lambda0)
    }
    x1=matrix(0,ncol=1,nrow=m)
    x2=matrix(0,ncol=1,nrow=m)
    y1=rep(-0.5,times=d)
    y2=rep(0.5,times=d)
    for(i in 1:m){
      x1[i,]=exp(-y1%*%x[i,])
      x2[i,]=exp(-y2%*%x[i,])
    }
    x3=colMeans(x1)
    x4=colMeans(x2)
    x5=cbind(x3,x4)
    x7=matrix(0,nrow=m,ncol=2)
    x71=matrix(0,nrow=m,ncol=d)
    for(i in 1:m){
      x71[i,]=rpois(n=d,lambda=lambda1)
    }
    for(i in 1:m){
      x7[i,]=c(exp(-y1%*%x71[i,]),exp(-y2%*%x71[i,]))
    }
    x8=colMeans(x7)
    repeat{
      c=2+1
      repeat{
        x9=matrix(0,c,d)
        h0=matrix(0,c,2)
        h1=matrix(0,c,2)
        for(i in 1:c){
          x9[i,]=rpois(n=d,lambda=lambda0)
        }
        for(i in 1:c){
          h0[i,]=c(exp(-y1%*%x9[i,]),exp(-y2%*%x9[i,]))-x5
          h1[i,]=c(exp(-y1%*%x9[i,]),exp(-y2%*%x9[i,]))-x8
        }
        z=numeric()
        repeat{
          for(i in 1:(c-2)){
            x10=h0[i:c,]
            x11=h1[i:c,]
            l0=el.test.newton(x=x10,mu=rep(0,2)) 
            l1=el.test.newton(x=x11,mu=rep(0,2)) 
            if(abs(sum(l0$wts)-1)<0.01&abs(sum(l1$wts)-1)<0.01){
              tl0=l0$`-2LLR`*max(1-l0$`-2LLR`/nrow(x10),0.5)
              tl1=l1$`-2LLR`*max(1-l1$`-2LLR`/nrow(x11),0.5)
              z[i]=exp(0.5*(tl0-tl1))
            }
          }
          z=na.omit(z)
          if(length(z)==0){
            x9=rbind(x9,rpois(n=d,lambda=lambda0))
            c=c+1
            print(c)
            h0=rbind(h0,c(exp(-y1%*%x9[i,]),exp(-y2%*%x9[i,]))-x5)
            h1=rbind(h1,c(exp(-y1%*%x9[i,]),exp(-y2%*%x9[i,]))-x8)
          }
          if(length(z)>0){
            if(sum(z)>threshold){
              false=false+1
              break
            }
          }
          if(length(z)>0){
            if(sum(z)<=threshold){
              x9=rbind(x9,rpois(n=d,lambda=lambda0))
              c=c+1
              print(c)
              h0=rbind(h0,c(exp(-y1%*%x9[i,]),exp(-y2%*%x9[i,]))-x5)
              h1=rbind(h1,c(exp(-y1%*%x9[i,]),exp(-y2%*%x9[i,]))-x8)
            }
          }
          if(c>=v){
            break
          }
        }
        if(false>=1){
          break
        }
        if(c>=v){
          break
        }
      }
      if(c>=v){
        break
      }
      if(false>=1){
        break
      }
    }
    if(false<1){
      nodetect=0
      repeat{
        x9=rbind(x9,rpois(n=d,lambda=lambda1))
        c=c+1
        h0=rbind(h0,c(exp(-y1%*%x9[c,]),exp(-y2%*%x9[c,]))-x5)
        h1=rbind(h1,c(exp(-y1%*%x9[c,]),exp(-y2%*%x9[c,]))-x8)
        z=numeric()
        for(i in 1:(c-2)){
          x10=h0[i:c,]
          x11=h1[i:c,]
          l0=el.test.newton(x=x10,mu=rep(0,2)) 
          l1=el.test.newton(x=x11,mu=rep(0,2)) 
          if(abs(sum(l0$wts)-1)<0.01&abs(sum(l1$wts)-1)<0.01){
            tl0=l0$`-2LLR`*max(1-l0$`-2LLR`/nrow(x10),0.5)
            tl1=l1$`-2LLR`*max(1-l1$`-2LLR`/nrow(x11),0.5)
            z[i]=exp(0.5*(tl0-tl1))
          }
        }
        z=na.omit(z)
        if(length(z)==0){
          x9=rbind(x9,rpois(n=d,lambda=lambda1))
          c=c+1
          print(c)
          h0=rbind(h0,c(exp(-y1%*%x9[c,]),exp(-y2%*%x9[c,]))-x5)
          h1=rbind(h1,c(exp(-y1%*%x9[c,]),exp(-y2%*%x9[c,]))-x8)
        }
        if(length(z)>0){
          if(sum(z)>threshold){
            break
          }
        }
        if(length(z)>0){
          if(sum(z)<=threshold){
            x9=rbind(x9,rpois(n=d,lambda=lambda1))
            c=c+1
            print(c)
            h0=rbind(h0,c(exp(-y1%*%x9[c,]),exp(-y2%*%x9[c,]))-x5)
            h1=rbind(h1,c(exp(-y1%*%x9[c,]),exp(-y2%*%x9[c,]))-x8)
          }
        }
        if(c>=101){
          break
        }
      }
      if(length(z)==0){
        z=c(0)
      }
      if(sum(z)<=threshold){
        repeat{
          z=numeric()
          x9=rbind(x9,rpois(n=d,lambda=lambda1))
          h0=rbind(h0,c(exp(-y1%*%x9[c,]),exp(-y2%*%x9[c,]))-x5)
          h1=rbind(h1,c(exp(-y1%*%x9[c,]),exp(-y2%*%x9[c,]))-x8)
          current0=h0[(nrow(h0)-99):nrow(h0),]
          current1=h1[(nrow(h1)-99):nrow(h1),]
          z=numeric()
          for(i in 1:(nrow(current0)-2)){
            x10=current0[i:nrow(current0),]
            x11=current1[i:nrow(current0),]
            l0=el.test.newton(x=x10,mu=rep(0,2)) 
            l1=el.test.newton(x=x11,mu=rep(0,2)) 
            if(abs(sum(l0$wts)-1)<0.01&abs(sum(l1$wts)-1)<0.01){
              tl0=l0$`-2LLR`*max(1-l0$`-2LLR`/nrow(x10),0.5)
              tl1=l1$`-2LLR`*max(1-l1$`-2LLR`/nrow(x11),0.5)
              z[i]=exp(0.5*(tl0-tl1))
            }
          }
          z=na.omit(z)
          if(length(z)==0){
            x9=rbind(x9,rpois(n=d,lambda=lambda1))
            c=c+1
            print(c)
            h0=rbind(h0,c(exp(-y1%*%x9[c,]),exp(-y2%*%x9[c,]))-x5)
            h1=rbind(h1,c(exp(-y1%*%x9[c,]),exp(-y2%*%x9[c,]))-x8)
          }
          if(length(z)>0){
            if(sum(z)>threshold){
              break
            }
          }
          if(length(z)>0){
            print(sum(z))
            if(sum(z)<=threshold){
              x9=rbind(x9,rpois(n=d,lambda=lambda1))
              c=c+1
              print(c)
              h0=rbind(h0,c(exp(-y1%*%x9[c,]),exp(-y2%*%x9[c,]))-x5)
              h1=rbind(h1,c(exp(-y1%*%x9[c,]),exp(-y2%*%x9[c,]))-x8)
            }
          }
          if(c>1000){
            nodetect=nodetect+1
            break
          }
        }
      }
      return(c(c-v,false,nodetect))
    }
    if(false>=1){
      return(c(NA,false,NA))
    }
  }
}


tel_laplace=function(d=2,m=100,threshold=200,lambda0=4,lambda1=4.5,trunction=1000){
  x=matrix(0,nrow=m,ncol=d)
  for(i in 1:m){
    x[i,]=rpois(n=d,lambda=lambda0)
  }
  x1=matrix(0,ncol=1,nrow=m)
  x2=matrix(0,ncol=1,nrow=m)
  y1=rep(-0.5,times=d)
  y2=rep(0.5,times=d)
  for(i in 1:m){
    x1[i,]=exp(-y1%*%x[i,])
    x2[i,]=exp(-y2%*%x[i,])
  }
  x3=colMeans(x1)
  x4=colMeans(x2)
  x5=cbind(x3,x4)
  x7=matrix(0,nrow=m,ncol=2)
  x71=matrix(0,nrow=m,ncol=d)
  for(i in 1:m){
    x71[i,]=rpois(n=d,lambda=lambda1)
  }
  for(i in 1:m){
    x7[i,]=c(exp(-y1%*%x71[i,]),exp(-y2%*%x71[i,]))
  }
  x8=colMeans(x7)
  c=2+1
  x9=matrix(0,c,d)
  h0=matrix(0,c,2)
  h1=matrix(0,c,2)
  for(i in 1:c){
    x9[i,]=rpois(n=d,lambda=lambda0)
  }
  for(i in 1:c){
    h0[i,]=c(exp(-y1%*%x9[i,]),exp(-y2%*%x9[i,]))-x5
    h1[i,]=c(exp(-y1%*%x9[i,]),exp(-y2%*%x9[i,]))-x8
  }
  z=numeric()
  repeat{
    for(i in 1:(c-2)){
      x10=h0[i:c,]
      x11=h1[i:c,]
      l0=el.test.newton(x=x10,mu=rep(0,2)) 
      l1=el.test.newton(x=x11,mu=rep(0,2)) 
      if(abs(sum(l0$wts)-1)<0.01&abs(sum(l1$wts)-1)<0.01){
        tl0=l0$`-2LLR`*max(1-l0$`-2LLR`/nrow(x10),0.5)
        tl1=l1$`-2LLR`*max(1-l1$`-2LLR`/nrow(x11),0.5)
        z[i]=exp(0.5*(tl0-tl1))
      }
    }
    z=na.omit(z)
    if(length(z)==0){
      x9=rbind(x9, rpois(n=d,lambda=lambda0))
      c=c+1
      print(c)
      h0=rbind(h0,c(exp(-y1%*%x9[c,]),exp(-y2%*%x9[c,]))-x5)
      h1=rbind(h1,c(exp(-y1%*%x9[c,]),exp(-y2%*%x9[c,]))-x8)
    }
    if(length(z)>0){
      if(sum(z)<=threshold){
        x9=rbind(x9, rpois(n=d,lambda=lambda0))
        c=c+1
        print(c)
        h0=rbind(h0,c(exp(-y1%*%x9[c,]),exp(-y2%*%x9[c,]))-x5)
        h1=rbind(h1,c(exp(-y1%*%x9[c,]),exp(-y2%*%x9[c,]))-x8)
      }
    }
    if(length(z)>0){
      if(sum(z)>threshold){
        break
      }
    }
    if(c>100){
      break
    }
  }
  if(length(z)==0){
    z=c(0)
  }
  if(sum(z)<=threshold){
    repeat{
      current0=h0[(nrow(h0)-99):nrow(h0),]
      current1=h1[(nrow(h1)-99):nrow(h1),]
      z=numeric()
      for(i in 1:(nrow(current0)-2)){
        x10=current0[i:nrow(current0),]
        x11=current1[i:nrow(current0),]
        l0=el.test.newton(x=x10,mu=rep(0,2)) 
        l1=el.test.newton(x=x11,mu=rep(0,2))
        if(abs(sum(l0$wts)-1)<0.01&abs(sum(l1$wts)-1)<0.01){
          tl0=l0$`-2LLR`*max(1-l0$`-2LLR`/nrow(x10),0.5)
          tl1=l1$`-2LLR`*max(1-l1$`-2LLR`/nrow(x11),0.5)
          z[i]=exp(0.5*(tl0-tl1))
        }
      }
      z=na.omit(z)
      if(length(z)==0){
        x9=rbind(x9,rpois(n=d,lambda=lambda0))
        c=c+1
        print(c)
        h0=rbind(h0,c(exp(-y1%*%x9[c,]),exp(-y2%*%x9[c,]))-x5)
        h1=rbind(h1,c(exp(-y1%*%x9[c,]),exp(-y2%*%x9[c,]))-x8)
      }
      if(length(z)>0){
        if(sum(z)>threshold){
          print(sum(z))
          break
        }
      }
      if(length(z)>0){
        print(sum(z))
        if(sum(z)<=threshold){
          x9=rbind(x9,rpois(n=d,lambda=lambda0))
          c=c+1
          print(c)
          h0=rbind(h0,c(exp(-y1%*%x9[c,]),exp(-y2%*%x9[c,]))-x5)
          h1=rbind(h1,c(exp(-y1%*%x9[c,]),exp(-y2%*%x9[c,]))-x8)
        }
      }
      if(c>=trunction){
        break
      }
    }
  }
  return(c)
}
