

opt_cusum=function(d=2,threshold=1,mu0=rep(0,times=d),mu1=rep(0.5,times=d),covar=diag(1,d,d)){
  c=0
  repeat{
    x=mvrnorm(n=1,mu=mu0,Sigma = covar)
    c=c+1
    print(c)
    x1=numeric()
    x2=numeric()
    c1=0
    repeat{
      if(c1==0){
        x2[1]=(t(x-mu0)%*%solve(covar)%*%(x-mu0)-t(x-mu1)%*%solve(covar)%*%(x-mu1))*0.5
        x1[1]=x2[1]
      }
      print(max(x1))
      if(max(x1)>threshold){
        break
      }
      if(max(x1)<0){
        break
      }
      if(c1>=1){
        x2[length(x2)+1]=(t(x[nrow(x),]-mu0)%*%solve(covar)%*%(x[nrow(x),]-mu0)-t(x[nrow(x),]-mu1)%*%solve(covar)%*%(x[nrow(x),]-mu1))*0.5
        for(i in 1:length(x2)){
          x1[i]=sum(x2[i:length(x2)])
        }
      }
      print(max(x1))
      if(max(x1)>threshold){
        break
      }
      if(max(x1)<0){
        break
      }
      x=rbind(x,mvrnorm(n=1,mu=mu0,Sigma = covar))
      c=c+1
      c1=c1+1
      print(c) 
    }
    if(max(x1)>threshold){
      break
    }
    if(c>10000){
      break
    }
  }
  return(c)
}



opt1_cusum=function(d=2,threshold=1,mu0=rep(0,times=d),mu1=rep(0.5,times=d),covar=diag(1,d,d)){
  false=0
  c=0
  repeat{
    repeat{
      x=mvrnorm(n=1,mu=mu0,Sigma = covar)
      c=c+1
      print(c)
      x1=numeric()
      x2=numeric()
      c1=0
      repeat{
        if(c1==0){
          x2[1]=(t(x-mu0)%*%solve(covar)%*%(x-mu0)-t(x-mu1)%*%solve(covar)%*%(x-mu1))*0.5
          x1[1]=x2[1]
        }
        print(max(x1))
        if(max(x1)>threshold){
          false=false+1
          break
        }
        if(max(x1)<0){
          break
        }
        if(c1>=1){
          x2[length(x2)+1]=(t(x[nrow(x),]-mu0)%*%solve(covar)%*%(x[nrow(x),]-mu0)-t(x[nrow(x),]-mu1)%*%solve(covar)%*%(x[nrow(x),]-mu1))*0.5
          for(i in 1:length(x2)){
            x1[i]=sum(x2[i:length(x2)])
          }
        }
        print(max(x1))
        if(max(x1)>threshold){
          false=false+1
          break
        }
        if(max(x1)<0){
          break
        }
        x=rbind(x,mvrnorm(n=1,mu=mu0,Sigma = covar))
        c=c+1
        c1=c1+1
        print(c) 
        if(c>=49){
          break
        }
        if(false>=1){
          break
        }
      }
      if(max(x1)>threshold){
        break
      }
      if(c>=49){
        break
      }
      if(false>=1){
        break
      }
    }
    if(c>=49){
      break
    }
    if(false>=1){
      break
    }
  }
  if(false<1){
  nodetect=0
  repeat{
    x=rbind(x,mvrnorm(n=1,mu=mu1,Sigma = covar))
    c=c+1
    x2[length(x2)+1]=(t(x[nrow(x),]-mu0)%*%solve(covar)%*%(x[nrow(x),]-mu0)-t(x[nrow(x),]-mu1)%*%solve(covar)%*%(x[nrow(x),]-mu1))*0.5
    for(i in 1:length(x2)){
      x1[i]=sum(x2[i:length(x2)])
    }
    if(max(x1)>threshold){
      break
    }
    if(max(x1)<0){
      break
    }
    if(c>1000){
      nodetect=1
      break
    }
  }
  
  if(max(x1)<=threshold){
    repeat{
      x=mvrnorm(n=1,mu=mu1,Sigma = covar)
      c=c+1
      print(c)
      x1=numeric()
      x2=numeric()
      c1=0
      repeat{
        if(c1==0){
          x2[1]=(t(x-mu0)%*%solve(covar)%*%(x-mu0)-t(x-mu1)%*%solve(covar)%*%(x-mu1))*0.5
          x1[1]=x2[1]
        }
        print(max(x1))
        if(max(x1)>threshold){
          break
        }
        if(max(x1)<0){
          break
        }
        if(c1>=1){
          x2[length(x2)+1]=(t(x[nrow(x),]-mu0)%*%solve(covar)%*%(x[nrow(x),]-mu0)-t(x[nrow(x),]-mu1)%*%solve(covar)%*%(x[nrow(x),]-mu1))*0.5
          for(i in 1:length(x2)){
            x1[i]=sum(x2[i:length(x2)])
          }
        }
        print(max(x1))
        if(max(x1)>threshold){
          break
        }
        if(max(x1)<0){
          break
        }
        x=rbind(x,mvrnorm(n=1,mu=mu1,Sigma = covar))
        c=c+1
        c1=c1+1
        print(c)
        if(c>1000){
          nodetect=1
          break
        }
      }
      if(max(x1)>threshold){
        break
      }
      if(c>1000){
        nodetect=1
        break
      }
    }
  }
  return(c(c-50,nodetect,false))
  }
  if(false>=1){
    return(c(NA,NA,false))
  }
}
